name: Build Native Libraries

on:
  push:
    paths:
      - '**.cpp'
      - '**.mm'
      - '**.yml'
      - '**gradle.*'
  pull_request:
    paths:
      - '**.cpp'
      - '**.mm'
      - '**.yml'
      - '**gradle.*'
  release:
    types:
      - published
  schedule:
    - cron:  '0 0 1 * *'
jobs:
  windows:
    name: Windows (Java 11)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew :auto-dark-mode-windows:build
      - name: Upload x86 artifact
        uses: actions/upload-artifact@v1
        with:
          name: auto-dark-mode-windows_x86.dll
          path: windows/build/libs/main/shared/windowsx86/auto-dark-mode-windows.dll
      - name: Upload x86-64 artifact
        uses: actions/upload-artifact@v1
        with:
          name: auto-dark-mode-windows_x86-64.dll
          path: windows/build/libs/main/shared/windowsx86-64/auto-dark-mode-windows.dll

  macOS:
    name: macOS (Java 11)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: setup-xcode
        uses: maxim-lobanov/setup-xcode@1.0
        with:
          xcode-version: 10.3 # set the latest available Xcode 10.3.*
      - name: Print SDK version
        run: xcodebuild -showsdks
      - name: Build
        run: ./gradlew :auto-dark-mode-macos:build
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: libauto-dark-mode-macos.dylib
          path: macos/build/libs/main/shared/libauto-dark-mode-macos.dylib
      - name: Print library information
        run: otool -l macos/build/libs/main/shared/libauto-dark-mode-macos.dylib
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build_logs
          path: macos/build/tmp
